---
title: "Effective Data Visualization for Actuaries"
author: "Brian Fannin, Jordan Bonner"
date: "5/08/2023"
output: html_document
---


```{r packages_fps, include = FALSE}
#' Install `pacman` package if not already loaded
setdiff(
  "pacman",
  rownames(installed.packages())
  ) |>
  install.packages()

#' Load (And Install if Necessary) Required Packages
pacman::p_load(
  httr, # For reading in TSA Data
  XML, # For reading in TSA Data
  raw,
  tidyverse,
  tidylog,
  datasauRus,
  gridExtra
)

#' Specify Image Filepath
path_png <- rstudioapi::getSourceEditorContext()$path |>
  dirname() |>
  dirname() |>
  paste0("/Images for Slides/")

#' Specify colors
pal_CAS <- c(
  "yellow" = "#FFD20D",
  "med_blue" = "#0071BC",
  "light_blue" = "#8DBBDD",
  "red" = "#ED254E",
  "dark_blue" = "#011936"
)
```


```{r anscombe_quartet}
#' Sample `Anscombe's Quartet` Scatterplots
d_anscombe <- datasets::anscombe |>
  mutate(id = row_number()) |>
  pivot_longer(-id) |>
  separate_wider_position(name, c(var_type = 1, dataset = 1)) |>
  pivot_wider(names_from = var_type, values_from = value)

d_anscombe |>
  ggplot(aes(x = x, y = y)) +
  geom_point(size = 2) +
  geom_smooth(method='lm', se = FALSE, fullrange = TRUE) +
  theme_bw(base_size = 20) +
  facet_wrap(~dataset, ncol = 2) +
  theme(
      strip.background = element_blank(),
      strip.text.x = element_blank()
  )

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "anscombe.png"
  ),
  width = 6,
  height = 4)
```

```{r seasonality}
#' Show `TSA Seasonality`
l_security  <- GET("https://www.tsa.gov/travel/passenger-volumes") |>
  content("text") |>
  readHTMLTable()
d_security <- l_security[[1]] |>
  as_tibble() |>
  pivot_longer(-Date, names_to = "year", values_to = "pax_char") |>
  mutate(date = mdy(paste(month(mdy(Date)),
                          day(mdy(Date)),
                          year,
                          sep = "-")),
         year = factor(year),
         week = week(date),
         date_axis =  mdy("1/1/20") + weeks(week - 1),
         pax = extract_numeric(pax_char)) |>
  group_by(year, week, date_axis) |>
  summarize(pax = mean(pax))
            
d_security |>
  ggplot(aes(x = date_axis, y = pax, color = year)) +
  geom_line(size = 1) +
  labs(
    x = "Date",
    y = "Mean Daily Count by Week",
    title = "TSA Checkpoint Numbers",
    color = "Year"
  ) +
  theme_minimal(base_size = 20) +
  theme(legend.position="bottom") +
  scale_x_date(#date_breaks = "3 months",
               labels = scales::date_format("%b")) +
  scale_y_continuous(labels = scales::comma) 

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "seasonality.png"
  ),
  width = 9,
  height = 6)
```


```{r residual}
#' Evaluate `Different Residual Plots`
fit <- d_anscombe |>
  nest_by(dataset) |>
  mutate(mod = list(lm(y ~ x, data = data))) %>%
  summarize(broom::tidy(mod)) |>
  select(dataset, term, estimate) |>
  mutate(term = if_else(term == "x", "slope", "intercept")) |>
  pivot_wider(names_from = term, values_from = estimate)

d_anscombe |>
  left_join(fit, by = "dataset") |>
  mutate(Fitted = intercept + x * slope,
         Residual = y - Fitted) |>
  ggplot(aes(x = Fitted, y = Residual)) +
  geom_point(size = 2) +
  theme_bw(base_size = 20) +
  facet_wrap(~dataset, ncol = 2) +
  theme(
      strip.background = element_blank(),
      strip.text.x = element_blank()
  ) +
  geom_hline(yintercept = 0,
             color = "blue",
             linewidth = 1)

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "anscombe_residuals.png"
  ),
  width = 6,
  height = 4)
```

```{r datasaurus}
#' Sample `datasauRus` Scatterplots
p_no_dino <- datasaurus_dozen |>
  filter(dataset != "dino") |>
  ggplot(aes(x = x, y = y, color = dataset)) +
    geom_point(size = 1) +
    theme_void() +
    theme(legend.position = "none") +
    facet_wrap(~dataset, ncol = 3) +
    theme(
        strip.background = element_blank(),
        strip.text.x = element_blank()
    )
p_dino <- datasaurus_dozen |>
  filter(dataset == "dino") |>
  ggplot(aes(x = x, y = y), size = 5) +
    geom_point(size = 3) +
    theme_void() +
    theme(legend.position = "none")

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "datasauRus_a.png"
  ),
  p_no_dino,
  width = 4,
  height = 4)
ggsave(
  paste0(
    path_png,
    "datasauRus_b.png"
  ),
  p_dino,
  width = 4,
  height = 4)
```

```{r big_picture}
group_count <- 24
set.seed(123)
data.frame(group = 1:group_count,
           starting_freq = rnorm(group_count, mean = 0.02, sd = 0.0075),
           trend = runif(group_count, 0.015, 0.025)) |>
  bind_rows(
    data.frame(group = group_count + 1,
               starting_freq = 0.0175,
               trend = runif(1, 0.07, 0.08))
  ) |>
  crossing(data.frame(year = 2016:2020)) |>
  group_by(group) |>
  mutate(year_tot = year - 2015,
         year_trend = rnorm(n(), mean = trend, sd = 0.015),
         freq_fac = 1 + year_trend,
         freq_running_total = cumprod(freq_fac),
         freq = starting_freq * freq_running_total,
         focus = if_else(group <= group_count, "0", "1")) |>
  ungroup() |>
  ggplot(aes(x = year, y = freq, group = group, color = focus)) +
  geom_line() +
  scale_color_manual(values = c("grey", "red")) +
  scale_y_continuous(limits = c(0, 0.035), labels = scales::percent) +
  labs(
    title = "Frequency by Group Over Time",
    x = "Year",
    y = "Frequency"
  ) +
  theme_classic(base_size = 20) +
  theme(legend.position = "none")


#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "big_picture.png"
  ),
  width = 6,
  height = 4)
```
```{r memory}
text_str <- "Frequency for Group C exposures is three times the higher than other groups."
memory_text <- ggpubr::ggparagraph(text = text_str, face = "italic", size = 18, color = "black") +
            theme(plot.margin = unit(c(t = 7, r = 3, b = 5, l = 3),"lines"))
memory_visual <- data.frame(group = c("A", "B", "C", "D"),
                            prob = c(1.1E-2, 0.9E-2, 3E-2, 1.1E-2),
                            callout = c("not_C", "not_C", "C", "not_C")) |>
  ggplot(aes(x = group, y = prob, fill = callout)) +
  geom_bar(stat = "identity", width = 0.75) +
  scale_fill_manual(values = c("red", "grey")) +
  labs(
    x = "Group",
    y = "Frequency"
  ) +
  theme_minimal(base_size = 20) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none") +
  scale_y_continuous(labels = scales::percent)

ggpubr::ggarrange(memory_text, memory_visual, 
          ncol = 2, nrow = 1)

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "memory.png"
  ),
  width = 6,
  height = 4)
```

```{r eg_a}
#' Sample `pressure` Scatterplot
pressure |>
  ggplot(aes(x = temperature, y = pressure)) +
  geom_point(size = 2) +
  geom_line() +
  theme_minimal() +
  labs(
    x = "Temperature",
    y = "Pressure",
    title = "Example Plot for Presentation A"
  )

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "example_plot_a.png"
  ),
  width = 6,
  height = 4)
```


```{r eg_b}
#' Sample `mtcars` scatterplot with a smoothed line
mtcars |>
  mutate(cyl = factor(cyl)) |>
  ggplot(aes(x = wt, y = mpg)) +
  geom_point(aes(color = cyl),
             size = 2) + 
  geom_smooth(method = "lm",
              formula = y ~ x,
              color = "black") +
  theme_minimal() +
  labs(
    x = "Weight",
    y = "Miles per Gallon",
    col = "# of Cylinders",
    title = "Example Plot for Presentation B"
  )

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "example_plot_b.png"
  ),
  width = 6,
  height = 4)
```


```{r eg_c}
#' Sample `mtcars` scatterplot with groups
iris |>
  mutate(Species = str_to_title(Species)) |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  geom_point(size = 2) +
  theme_minimal() +
  labs(
    x = "Sepal Length",
    y = "Sepal Width",
    col = "Species",
    title = "Example Plot for Presentation C"
  )

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "example_plot_c.png"
  ),
  width = 6,
  height = 4)
```



```{r eg_d}
#' Sample `PPA_LossDevelopment` and `PPA_LossDevelopment` line chart
PPA_LossDevelopment |>
  arrange(AccidentYear, Lag) |>
  group_by(AccidentYear) |>
  mutate(IncremLoss = ReportedLoss-replace_na(lag(ReportedLoss), 0),
         Lag = factor(Lag)) |>
  ggplot(aes(x = ReportedLoss, y = IncremLoss)) +
  geom_point() +
  facet_grid(~Lag) +
  geom_smooth(method = "lm",
              formula = y ~ x,
              color = "black",
              se = FALSE) +
  theme_minimal() +
  labs(
    x = "Cumulative Loss",
    y = "Incremental Loss",
    col = "Dev. Pd.",
    title = "Example Plot for Presentation D"
  )
PPA_LossTrend |>
  mutate(freq = ClosedClaimCount / EarnedExposure) |>
  ggplot(aes(x = YearEndingQuarter, y = freq)) +
  geom_line() +
  # scale_y_continuous(limits = c(0, 0.075)) +
  theme_minimal() +
  labs(
    x = "Year Ending Quarter",
    y = "Frequency",
    title = "Example Plot for Presentation D"
  )

#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "example_plot_d.png"
  ),
  width = 6,
  height = 4)
```



```{r indication}

PPA_AccidentYear |>
  cbind(
    data.frame(
      rate_level_adj = c(1.2161, 1.2176, 1.1311, 1.0892, 1.0991),
      prem_trend = c(1.1342, 1.1116, 1.0879, 1.0663, 1.0452),
      loss_dev = c(1.0000, 0.9899, 1.0003, 1.0282, 1.0966),
      loss_trend = c(0.9912, 0.9962, 1.0012, 1.0062, 1.0113),
      ulae_ratio = rep(1.143, 5)
    )
  ) |>
  transmute(
    AccidentYear,
    EarnedPremium,
    ReportedLosses,
    crl = (1 / rate_level_adj - 1) * ReportedLosses,
    trend = (loss_trend / prem_trend - 1) * ReportedLosses,
    dev = (loss_dev - 1) * ReportedLosses,
    ulae = (ulae_ratio - 1) * ReportedLosses
  ) |>
  pivot_longer(-(AccidentYear:EarnedPremium),
               names_to = "field") |>
  mutate(ratio = value / EarnedPremium) |>
  select(-EarnedPremium, -value) |>
  pivot_wider(names_from = field, values_from = ratio)
  ggplot(aes(x = AccidentYear, y = ratio, fill = field)) +
  geom_bar(stat = "identity")
  

# Can we make negative values below the line, and show net on top? Or even perhaps
# show empty boxes above where loss was reduced


# Proj EP @ CRL = EP * CRL * Trend

# Proj Ult L & LAE = Rep L * Dev * Trend * ULAE

# LR = L / EP

PPA_AccidentYear |>
  cbind(
    data.frame(
      loss_dev = c(1.0000, 1.0000, 1.0003, 1.0282, 1.0966),
      loss_trend = c(1.0000, 1.0000, 1.0012, 1.0062, 1.0113),
      ulae_ratio = rep(1.143, 5)
    )
  ) |>
  transmute(
    AccidentYear,
    EarnedPremium,
    ReportedLosses,
    trend = (loss_trend - 1) * ReportedLosses,
    dev = (loss_dev - 1) * ReportedLosses,
    ulae = (ulae_ratio - 1) * ReportedLosses
  ) |>
  pivot_longer(-(AccidentYear:EarnedPremium),
               names_to = "field") |>
  mutate(ratio = value / EarnedPremium) |>
  select(-EarnedPremium, -value) |>
  # pivot_wider(names_from = field, values_from = ratio)
  ggplot(aes(x = AccidentYear, y = ratio, fill = field)) +
  geom_bar(stat = "identity")

#' Save to Image Folder
# ggsave(
#   paste0(
#     path_png,
#     "example_plot_d.png"
#   ),
#   width = 6,
#   height = 4)
```



```{r simple_fixes}
#' Fake fitted severitiy data
set.seed(123)
severity_fit_data <- tibble(
  x = seq(1, 100E3, 1),
  prob = dlnorm(seq(1, 100E3, 1),
                meanlog = 10,
                sdlog = 1))
severity_data <- tibble(
  x = runif(500E3),
  lnorm_mean = rnorm(500E3, mean = 10, sd = 0.5),
  lnorm_sigma = rnorm(500E3, mean = 1, sd = 0.10)) |>
  mutate(loss = qlnorm(x, meanlog = lnorm_mean, sdlog = lnorm_sigma)) |>
  filter(loss <= 100E3) |>
  head(100E3)



#' First - a bad plot of `severity`
sev_plot <- severity_data |>
  ggplot() +
  geom_histogram(aes(x = loss, after_stat(density)),
                 binwidth = 0.5E3) +
  stat_function(fun = dlnorm,
                args = list(meanlog = 10, sdlog = 1.0)) #+
  # stat_function(fun = dgamma,
  #               args = list(shape = 1.5, scale = 5000 * 2 / 1.5))
sev_plot
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "severity_1_bad.png"
  ),
  width = 6,
  height = 4)



#' Made better with a `titles`...
sev_plot +
  labs(
    x = "Severity",
    y = "Density",
    title = "Fitted Severity Curve"
  )
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "severity_2_good.png"
  ),
  width = 6,
  height = 4)



#' Made better with `udpating axes`...
sev_plot +
  labs(
    x = "Severity",
    title = "Fitted Severity Curve"
  ) +
  scale_x_continuous(labels = scales::comma) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "severity_3_better.png"
  ),
  width = 6,
  height = 4)



#' Made better with being `larger`...
#' Note that adding teme adds in y-axis.
sev_plot <- sev_plot +
  labs(
    x = "Severity",
    title = "Fitted Severity Curve"
  ) +
  theme_minimal(base_size = 20) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_x_continuous(labels = scales::comma) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())
sev_plot
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "severity_4_even_better.png"
  ),
  width = 6,
  height = 4)



#' Made better with adding `colors`...
severity_data |>
  ggplot() +
  geom_histogram(aes(x = loss, after_stat(density)),
                 binwidth = 0.5E3,
                 fill = pal_CAS["light_blue"]) +
  stat_function(fun = dlnorm,
                args = list(meanlog = 10, sdlog = 1.0),
                color = pal_CAS["dark_blue"]) +
  labs(
    x = "Severity",
    title = "Fitted Severity Curve"
  ) +
  theme_minimal(base_size = 20) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_x_continuous(labels = scales::comma) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "severity_5_best.png"
  ),
  width = 6,
  height = 4)
```



```{r axes_2_or_1}
#' Fake data for plotting two axes
relativity_data <- tibble(
  level = paste0("Cat. ", LETTERS[1:6]),
  ee = c(2.5E3, 20E3, 54E3, 42E3, 13E3, 3E3),
  rel = c(0.85, 0.90, 1.0, 1.2, 1.3, 1.8)
  )
adj_ratio <- max(relativity_data$ee) / max(relativity_data$rel)


#' First - a plot of just `relativity`
relativity_data |>
  ggplot(aes(x = level,
             y = rel,
             group = 1)) +
  geom_line(linewidth = 1,
            color = pal_CAS["med_blue"]) +
  scale_y_continuous(limits = c(0, 2)) +
  theme_minimal() +
  labs(
    x = "Category",
    y = "Indicated Relativity",
    title = "Indicated Relativity by Category"
  )
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "two_axes__rels_only.png"
  ),
  width = 6,
  height = 4)


#' Second - a plot of just `exposures`
relativity_data |>
  ggplot(aes(x = level,
             y = ee,
             group = 1)) +
  geom_bar(stat = "identity",
           width = 0.6,
           fill = "grey") +
  scale_y_continuous(limits = c(0, 60E3),
                     labels = scales::comma) +
  theme_minimal() +
  labs(
    x = "Category",
    y = "Exposures",
    title = "Indicated Relativity by Exposure Count & Category"
  )
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "two_axes__ee_only.png"
  ),
  width = 6,
  height = 4)


#' Third - a plot of `relativity` vs `exposures`
relativity_data |>
  ggplot(aes(x = level, group = 1)) +
  geom_bar(aes(y = ee / adj_ratio),
           stat = "identity",
           width = 0.6,
           fill = "grey") +
  geom_line(aes(y = rel),
            linewidth = 1,
            color = pal_CAS["med_blue"]) +
  scale_y_continuous(limits = c(0, 2),
                     sec.axis = sec_axis(~ . * adj_ratio,
                                         name = "Exposures",
                                         labels = scales::comma)) +
  theme_minimal() +
  labs(
    x = "Category",
    y = "Indicated Relativity",
    title = "Indicated Relativity by Category"
  )
#' Save to Image Folder
ggsave(
  paste0(
    path_png,
    "two_axes__rels_and_ee.png"
  ),
  width = 6,
  height = 4)


```